language: go

env:
  - GO111MODULE=on

go:
  - 1.x
  - master

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

script:
  - go test -v -race -timeout=10s ./...
  - golangci-lint
