on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
